// Export all services
export { default as authService } from './authService'
export { default as movieService } from './movieService'
export { default as watchlistService } from './watchlistService'
export { default as reviewService } from './reviewService'
export { default as notificationService } from './notificationService'
export { default as userService } from './userService'
export { default as paymentService } from './paymentService'
export { default as recommendationService } from './recommendationService'
export { default as historyService } from './historyService'
export { default as genreService } from './genreService'
export { default as adminService } from './adminService'
export { default as chatService } from './chatService'
export { commentService } from './commentService'